packages:
  - '.'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@aoles-gl/core@0.1.0'
  - '@aoles-gl/effects@0.1.0'
  - '@aoles-gl/react@0.1.0'
  - '@aoles-gl/theme@0.1.0'
  - '@aoles-gl/ui@0.1.0'

